services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: phantom
      POSTGRES_PASSWORD: phantom
      POSTGRES_DB: phantom_csm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"    # AMQP (app)
      - "15672:15672"  # dashboard web
    environment:
      RABBITMQ_DEFAULT_USER: phantom
      RABBITMQ_DEFAULT_PASS: phantom

volumes:
  postgres_data:
