name: phantom-csm-infra
description: Hetzner Cloud infrastructure for phantom-csm (managed by Pulumi)
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
