all:
  children:
    phantom:
      hosts:
        phantom-server:
          ansible_host: "{{ phantom_ip }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/phantom-csm.pem
          ansible_python_interpreter: /usr/bin/python3
